name: Build

on:
  push:
    branches: [ master ]

# cancel previous workflows, run only one workflow
#concurrency:
##group: build-${{ github.event.push.number || github.event.pull_request.number || github.ref }}
##cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        token: "${{ secrets.GITHUB_TOKEN }}"
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm i -g gulp-cli typescript npm ts-node
        npm install
        npm i git+https://github.com/dimaslanjaka/persistent-cache#improve2

    - name: Build
      run: npm run build
      
    - name: remove caches
      run: |
        git rm --cached -r package.json
        git rm --cached -r package-lock.json
        git config user.name dimaslanjaka
        git config user.email dimaslanjaka@gmail.com
        git push origin master

    - name: Re-deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.3.0
      if: ${{ false }}
      with:
        branch: master # The branch the action should deploy to.
        folder: . # The folder the action should deploy.
        force: false # merge instead delete old files
        token: "${{ secrets.GITHUB_TOKEN }}"
